"""Generate Telegraf TOML config dynamically from a Simantha scenario config.

Mirrors the ISA-95/ISO 23247 aligned OPC UA address space built by
build_opcua_server() in opcua_server.py.

Produces a telegraf.conf that polls all nodes for any number of machines,
buffers, scrap sinks, and optional features (SPC, failure modes, quality
routing, shifts).

Usage as CLI:
    python generate_telegraf_conf.py --config ../../config/line_models.yaml \
        --scenario full_feature_line --output telegraf.conf

Usage as library:
    from generate_telegraf_conf import generate_telegraf_conf
    conf_text = generate_telegraf_conf(config_dict)
"""
import argparse
import os
import sys
import textwrap


def _node(name, identifier, tags=None):
    """Format a single Telegraf OPC UA node entry."""
    parts = [
        f'name="{name}"',
        'namespace="2"',
        'identifier_type="s"',
        f'identifier="{identifier}"',
    ]
    if tags:
        tag_items = ", ".join(f'{k}="{v}"' for k, v in tags.items())
        parts.append(f"tags={{{tag_items}}}")
    return "    {" + ", ".join(parts) + "},"


def _equip_prefix(config):
    """Build the ISA-95 equipment prefix from config, matching build_opcua_server()."""
    ent = config.get("enterprise", "WeylandIndustries")
    site = config.get("site", "LV426_Colony")
    area = config.get("area", "AtmosphereProcessor01")
    line = config.get("line_name", "Nostromo_BioProductPakaging")
    return f"{ent}.{site}.{area}.{line}_Equipment"


def generate_telegraf_conf(config,
                           opcua_endpoint="opc.tcp://simantha:4840/simantha/",
                           influxdb_url="http://influxdb:8086",
                           influxdb_token="simantha-dev-token",
                           influxdb_org="simantha",
                           influxdb_bucket="manufacturing",
                           run_id=""):
    """Generate Telegraf TOML config from a scenario config dict.

    Args:
        config: Scenario config dict (machines, buffers, scrap_sinks, shifts, etc.)
        opcua_endpoint: OPC UA server endpoint URL
        influxdb_url: InfluxDB server URL
        influxdb_token: InfluxDB authentication token
        influxdb_org: InfluxDB organization
        influxdb_bucket: InfluxDB bucket name

    Returns:
        The full telegraf.conf content as a string.
    """
    lines = []

    machines = config.get("machines", [])
    buffers = config.get("buffers", [])
    scrap_sinks = config.get("scrap_sinks", [])
    has_shifts = "shifts" in config

    # ISA-95 base path for all equipment nodes
    ep = _equip_prefix(config)

    lines.append(textwrap.dedent(f"""\
        # Telegraf OPC UA -> InfluxDB pipeline for Simantha Digital Twin
        # ISA-95/ISO 23247 aligned address space
        #
        # AUTO-GENERATED by generate_telegraf_conf.py
        # {len(machines)} machines, {len(buffers)} buffers, {len(scrap_sinks)} scrap sinks
        # Shifts: {"yes" if has_shifts else "no"}
        # RunID: {run_id or "(not set)"}

        [global_tags]
          run_id = "{run_id}"

        [agent]
          interval = "1s"
          flush_interval = "5s"

        [[outputs.influxdb_v2]]
          urls = ["{influxdb_url}"]
          token = "{influxdb_token}"
          organization = "{influxdb_org}"
          bucket = "{influxdb_bucket}"

        [[inputs.opcua]]
          name = "opcua"
          endpoint = "{opcua_endpoint}"
          security_policy = "None"
          security_mode = "None"
          connect_timeout = "30s"
          request_timeout = "10s"

          nodes = ["""))

    # --- Identification ---
    lines.append("    # " + "=" * 73)
    lines.append("    # IDENTIFICATION")
    lines.append("    # " + "=" * 73)
    lines.append(_node("RunID", f"{ep}.Identification.RunID"))
    lines.append("")

    # --- OperationsState ---
    lines.append("    # " + "=" * 73)
    lines.append("    # OPERATIONS STATE")
    lines.append("    # " + "=" * 73)
    lines.append(_node("SimTime", f"{ep}.OperationsState.SimTime"))
    lines.append(_node("LineState", f"{ep}.OperationsState.LineState"))
    lines.append(_node("LineMode", f"{ep}.OperationsState.LineMode"))
    lines.append("")

    # --- Recipe (OperationsState/Recipe) ---
    rcp = f"{ep}.OperationsState.Recipe"
    lines.append("    # Recipe")
    lines.append(_node("Recipe_Name", f"{rcp}.RecipeName"))
    lines.append(_node("Recipe_Description", f"{rcp}.RecipeDescription"))
    lines.append(_node("Recipe_Segment", f"{rcp}.SegmentName"))
    lines.append(_node("Recipe_SegmentIndex", f"{rcp}.SegmentIndex"))
    lines.append(_node("Recipe_TotalSegments", f"{rcp}.TotalSegments"))
    lines.append(_node("Recipe_SegmentTimeRemaining", f"{rcp}.SegmentTimeRemaining"))
    lines.append(_node("Recipe_SegmentQuantityTarget", f"{rcp}.SegmentQuantityTarget"))
    lines.append(_node("Recipe_SegmentQuantityProduced", f"{rcp}.SegmentQuantityProduced"))
    lines.append(_node("Recipe_SegmentStopMode", f"{rcp}.SegmentStopMode"))
    lines.append(_node("Recipe_ChangeoverState", f"{rcp}.ChangeoverState"))
    lines.append(_node("Recipe_LastChangeoverPlanned", f"{rcp}.LastChangeoverPlanned"))
    lines.append(_node("Recipe_LastChangeoverActual", f"{rcp}.LastChangeoverActual"))
    lines.append("")

    # --- OperationsPerformance ---
    lines.append("    # Operations Performance")
    lines.append(_node("Throughput", f"{ep}.OperationsPerformance.Throughput"))
    lines.append(_node("TotalWIP", f"{ep}.OperationsPerformance.TotalWIP"))
    lines.append(_node("TotalScrap", f"{ep}.OperationsPerformance.TotalScrap"))
    lines.append(_node("ScrapRate", f"{ep}.OperationsPerformance.ScrapRate"))
    lines.append("")

    # --- Line OEE ---
    lines.append("    # Line OEE")
    lines.append(_node("LineOEE", f"{ep}.OEE.OEE"))
    lines.append(_node("LineAvailability", f"{ep}.OEE.Availability"))
    lines.append(_node("LinePerformance", f"{ep}.OEE.Performance"))
    lines.append(_node("LineQuality", f"{ep}.OEE.Quality"))
    lines.append(_node("LineGoodParts", f"{ep}.OEE.GoodPartCount"))
    lines.append(_node("LineDefectiveParts", f"{ep}.OEE.DefectivePartCount"))
    lines.append("")

    # --- EventLog ---
    lines.append("    # Event Log")
    lines.append(_node("TotalEventsGenerated", f"{ep}.EventLog.TotalEventsGenerated"))
    lines.append("")

    # --- SupportFunctions: Maintenance ---
    sf = f"{ep}.SupportFunctions"
    lines.append("    # Maintenance (SupportFunctions)")
    lines.append(_node("Sys_MaintenanceActive", f"{sf}.Maintenance.MaintenanceActive"))
    lines.append(_node("Sys_QueueLength", f"{sf}.Maintenance.QueueLength"))
    lines.append(_node("Sys_TotalRepairs", f"{sf}.Maintenance.TotalRepairs"))

    # --- Per-machine nodes (under Resources) ---
    res = f"{ep}.Resources"
    for idx, machine_cfg in enumerate(machines, start=1):
        mp = f"M{idx}"  # Abbreviated prefix for InfluxDB field names
        mn = f"M{idx}_Equipment"  # ISA-95 equipment node name
        p = f"{res}.{mn}"  # Full OPC UA path
        tags = {"source": f"Machine{idx}", "source_type": "machine"}

        enable_degradation = machine_cfg.get("enable_degradation", False)
        enable_advanced = machine_cfg.get("enable_advanced_failures", False)
        enable_spc = machine_cfg.get("enable_spc", False)
        qr = machine_cfg.get("quality_routing", {})
        enable_qr = qr.get("enabled", False)

        lines.append("")
        lines.append("    # " + "=" * 73)
        lines.append(f"    # MACHINE {idx} ({mn})")
        lines.append("    # " + "=" * 73)

        # OperationsState (1-3)
        lines.append("    # OperationsState")
        lines.append(_node(f"{mp}_State", f"{p}.OperationsState.State", tags))

        if enable_degradation or enable_advanced:
            lines.append(_node(f"{mp}_HealthState", f"{p}.OperationsState.HealthState", tags))
            lines.append(_node(f"{mp}_HealthPercent", f"{p}.OperationsState.HealthPercent", tags))
        lines.append("")

        # OperationsPerformance (9)
        lines.append("    # OperationsPerformance")
        lines.append(_node(f"{mp}_PartCount", f"{p}.OperationsPerformance.PartCount", tags))
        lines.append(_node(f"{mp}_Utilisation", f"{p}.OperationsPerformance.Utilisation", tags))
        lines.append(_node(f"{mp}_TargetPPM", f"{p}.OperationsPerformance.TargetPPM", tags))
        lines.append(_node(f"{mp}_ActualPPM", f"{p}.OperationsPerformance.ActualPPM", tags))
        lines.append(_node(f"{mp}_BlockedTime", f"{p}.OperationsPerformance.BlockedTime", tags))
        lines.append(_node(f"{mp}_StarvedTime", f"{p}.OperationsPerformance.StarvedTime", tags))
        lines.append(_node(f"{mp}_DownTime", f"{p}.OperationsPerformance.DownTime", tags))
        lines.append(_node(f"{mp}_ProcessingTime", f"{p}.OperationsPerformance.ProcessingTime", tags))
        lines.append(_node(f"{mp}_IdleTime", f"{p}.OperationsPerformance.IdleTime", tags))
        lines.append("")

        # OEE (7)
        lines.append("    # OEE")
        lines.append(_node(f"{mp}_OEE", f"{p}.OEE.OEE", tags))
        lines.append(_node(f"{mp}_Availability", f"{p}.OEE.Availability", tags))
        lines.append(_node(f"{mp}_Performance", f"{p}.OEE.Performance", tags))
        lines.append(_node(f"{mp}_Quality", f"{p}.OEE.Quality", tags))
        lines.append(_node(f"{mp}_GoodParts", f"{p}.OEE.GoodPartCount", tags))
        lines.append(_node(f"{mp}_DefectParts", f"{p}.OEE.DefectivePartCount", tags))
        lines.append(_node(f"{mp}_TheoreticalOutput", f"{p}.OEE.TheoreticalOutput", tags))
        lines.append("")

        # Alarms (4)
        lines.append("    # Alarms")
        lines.append(_node(f"{mp}_ActiveAlarmCount", f"{p}.Alarms.ActiveAlarmCount", tags))
        lines.append(_node(f"{mp}_MachineFailureActive", f"{p}.Alarms.MachineFailureActive", tags))
        lines.append(_node(f"{mp}_MaintenanceActive", f"{p}.Alarms.MaintenanceActive", tags))
        lines.append(_node(f"{mp}_QualityAlertActive", f"{p}.Alarms.QualityAlertActive", tags))

        # Failure Modes (1 + 4*n) + Maintenance Strategy (4)
        if enable_advanced:
            failure_modes = machine_cfg.get("failure_modes", [])
            lines.append("")
            lines.append("    # Failure Modes")
            lines.append(_node(f"{mp}_ActiveFailureMode", f"{p}.FailureModes.ActiveFailureMode", tags))
            for fm in failure_modes:
                fm_name = fm["name"]
                cap = fm_name.capitalize()
                lines.append(_node(f"{mp}_{cap}FailureCount", f"{p}.FailureModes.{cap}FailureCount", tags))
                lines.append(_node(f"{mp}_{cap}TotalDowntime", f"{p}.FailureModes.{cap}TotalDowntime", tags))
                lines.append(_node(f"{mp}_{cap}MTBF", f"{p}.FailureModes.{cap}MTBF", tags))
                lines.append(_node(f"{mp}_{cap}MTTR", f"{p}.FailureModes.{cap}MTTR", tags))
            lines.append("")

            # Maintenance Strategy (4)
            lines.append("    # Maintenance Strategy")
            lines.append(_node(f"{mp}_StrategyType", f"{p}.MaintenanceStrategy.StrategyType", tags))
            lines.append(_node(f"{mp}_NextPMScheduled", f"{p}.MaintenanceStrategy.NextPMScheduled", tags))
            lines.append(_node(f"{mp}_PMCount", f"{p}.MaintenanceStrategy.PMCount", tags))
            lines.append(_node(f"{mp}_CMCount", f"{p}.MaintenanceStrategy.CMCount", tags))

        # Quality Routing (5)
        if enable_qr:
            lines.append("")
            lines.append("    # Quality Routing")
            lines.append(_node(f"{mp}_ScrapCount", f"{p}.QualityRouting.ScrapCount", tags))
            lines.append(_node(f"{mp}_ReworkCount", f"{p}.QualityRouting.ReworkCount", tags))
            lines.append(_node(f"{mp}_ReworkSuccessCount", f"{p}.QualityRouting.ReworkSuccessCount", tags))
            lines.append(_node(f"{mp}_ReworkSuccessRate", f"{p}.QualityRouting.ReworkSuccessRate", tags))
            lines.append(_node(f"{mp}_GoodCount", f"{p}.QualityRouting.GoodCount", tags))

        # SPC (17)
        if enable_spc:
            lines.append("")
            lines.append("    # SPC - X-bar Chart")
            lines.append(_node(f"{mp}_SPC_XBar", f"{p}.SPC.XBarChart.XBar", tags))
            lines.append(_node(f"{mp}_SPC_XBar_UCL", f"{p}.SPC.XBarChart.UCL", tags))
            lines.append(_node(f"{mp}_SPC_XBar_CL", f"{p}.SPC.XBarChart.CL", tags))
            lines.append(_node(f"{mp}_SPC_XBar_LCL", f"{p}.SPC.XBarChart.LCL", tags))
            lines.append("    # SPC - R Chart")
            lines.append(_node(f"{mp}_SPC_Range", f"{p}.SPC.RChart.Range", tags))
            lines.append(_node(f"{mp}_SPC_R_UCL", f"{p}.SPC.RChart.UCL", tags))
            lines.append(_node(f"{mp}_SPC_R_CL", f"{p}.SPC.RChart.CL", tags))
            lines.append(_node(f"{mp}_SPC_R_LCL", f"{p}.SPC.RChart.LCL", tags))
            lines.append("    # SPC - Capability")
            lines.append(_node(f"{mp}_SPC_Cp", f"{p}.SPC.Capability.Cp", tags))
            lines.append(_node(f"{mp}_SPC_Cpk", f"{p}.SPC.Capability.Cpk", tags))
            lines.append(_node(f"{mp}_SPC_Pp", f"{p}.SPC.Capability.Pp", tags))
            lines.append(_node(f"{mp}_SPC_Ppk", f"{p}.SPC.Capability.Ppk", tags))
            lines.append(_node(f"{mp}_SPC_SigmaLevel", f"{p}.SPC.Capability.SigmaLevel", tags))
            lines.append("    # SPC - Status")
            lines.append(_node(f"{mp}_SPC_InControl", f"{p}.SPC.Status.InControl", tags))
            lines.append(_node(f"{mp}_SPC_Violations", f"{p}.SPC.Status.Violations", tags))
            lines.append(_node(f"{mp}_SPC_TotalSamples", f"{p}.SPC.Status.TotalSamples", tags))
            lines.append(_node(f"{mp}_SPC_NumSubgroups", f"{p}.SPC.Status.NumSubgroups", tags))

    # --- Per-buffer StorageUnit nodes ---
    for idx, buffer_cfg in enumerate(buffers, start=1):
        bp = f"B{idx}"
        bn = f"B{idx}_StorageUnit"
        b = f"{res}.{bn}"
        tags = {"source": f"Buffer{idx}", "source_type": "buffer"}

        lines.append("")
        lines.append("    # " + "=" * 73)
        lines.append(f"    # BUFFER {idx} ({bn})")
        lines.append("    # " + "=" * 73)
        lines.append(_node(f"{bp}_Level", f"{b}.CurrentLevel", tags))
        lines.append(_node(f"{bp}_Capacity", f"{b}.Capacity", tags))

    # --- Scrap StorageUnit nodes ---
    if scrap_sinks:
        lines.append("")
        lines.append("    # " + "=" * 73)
        lines.append("    # SCRAP BINS (StorageUnits)")
        lines.append("    # " + "=" * 73)
        for idx, scrap_cfg in enumerate(scrap_sinks, start=1):
            scrap_name = scrap_cfg["name"]
            unit_name = f"{scrap_name}_StorageUnit"
            tags = {"source": scrap_name, "source_type": "scrap"}
            lines.append(_node(f"Scrap{idx}_Level", f"{res}.{unit_name}.CurrentLevel", tags))

    # --- Shift nodes (under SupportFunctions/ShiftManagement) ---
    if has_shifts:
        sm = f"{sf}.ShiftManagement"
        lines.append("")
        lines.append("    # " + "=" * 73)
        lines.append("    # SHIFTS (SupportFunctions/ShiftManagement)")
        lines.append("    # " + "=" * 73)

        # Shift tracking (7)
        lines.append("    # Shift tracking")
        lines.append(_node("Shift_Number", f"{sm}.CurrentShiftNumber"))
        lines.append(_node("Shift_Name", f"{sm}.CurrentShiftName"))
        lines.append(_node("Shift_StartTime", f"{sm}.ShiftStartTime"))
        lines.append(_node("Shift_EndTime", f"{sm}.ShiftEndTime"))
        lines.append(_node("Shift_Duration", f"{sm}.ShiftDuration"))
        lines.append(_node("Shift_Elapsed", f"{sm}.ShiftElapsedTime"))
        lines.append(_node("Shift_Remaining", f"{sm}.ShiftTimeRemaining"))
        lines.append("")

        # Current shift metrics (8)
        lines.append("    # Current shift metrics")
        lines.append(_node("CurrShift_Parts", f"{sm}.CurrentShift.PartsProduced"))
        lines.append(_node("CurrShift_GoodParts", f"{sm}.CurrentShift.GoodParts"))
        lines.append(_node("CurrShift_DefParts", f"{sm}.CurrentShift.DefectiveParts"))
        lines.append(_node("CurrShift_DefRate", f"{sm}.CurrentShift.DefectRate"))
        lines.append(_node("CurrShift_Avail", f"{sm}.CurrentShift.Availability"))
        lines.append(_node("CurrShift_Perf", f"{sm}.CurrentShift.Performance"))
        lines.append(_node("CurrShift_Qual", f"{sm}.CurrentShift.Quality"))
        lines.append(_node("CurrShift_OEE", f"{sm}.CurrentShift.OEE"))
        lines.append("")

        # Previous shift metrics (7)
        lines.append("    # Previous shift metrics")
        lines.append(_node("PrevShift_Number", f"{sm}.PreviousShift.ShiftNumber"))
        lines.append(_node("PrevShift_Name", f"{sm}.PreviousShift.ShiftName"))
        lines.append(_node("PrevShift_Parts", f"{sm}.PreviousShift.PartsProduced"))
        lines.append(_node("PrevShift_GoodParts", f"{sm}.PreviousShift.GoodParts"))
        lines.append(_node("PrevShift_DefParts", f"{sm}.PreviousShift.DefectiveParts"))
        lines.append(_node("PrevShift_DefRate", f"{sm}.PreviousShift.DefectRate"))
        lines.append(_node("PrevShift_OEE", f"{sm}.PreviousShift.OEE"))
        lines.append("")

        # Shift totals (5)
        lines.append("    # Shift totals")
        lines.append(_node("ShiftTotal_Parts", f"{sm}.Totals.TotalPartsProduced"))
        lines.append(_node("ShiftTotal_GoodParts", f"{sm}.Totals.TotalGoodParts"))
        lines.append(_node("ShiftTotal_DefParts", f"{sm}.Totals.TotalDefectiveParts"))
        lines.append(_node("ShiftTotal_DefRate", f"{sm}.Totals.TotalDefectRate"))
        lines.append(_node("ShiftTotal_Completed", f"{sm}.Totals.TotalShiftsCompleted"))

    # Close the nodes array
    lines.append("  ]")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate Telegraf config from Simantha scenario"
    )
    parser.add_argument("--config", required=True,
                        help="Path to line_models.yaml")
    parser.add_argument("--scenario", required=True,
                        help="Scenario name (e.g., full_feature_line)")
    parser.add_argument("--output", default=None,
                        help="Output file path (default: stdout)")
    parser.add_argument("--endpoint",
                        default="opc.tcp://simantha:4840/simantha/",
                        help="OPC UA endpoint URL")
    parser.add_argument("--influxdb-url", default="http://influxdb:8086",
                        help="InfluxDB URL")
    parser.add_argument("--influxdb-token", default="simantha-dev-token",
                        help="InfluxDB token")
    parser.add_argument("--influxdb-org", default="simantha",
                        help="InfluxDB organization")
    parser.add_argument("--influxdb-bucket", default="manufacturing",
                        help="InfluxDB bucket")
    parser.add_argument("--run-id", default="",
                        help="Run ID for global_tags (default: empty)")
    args = parser.parse_args()

    # Add src/ to path so we can optionally use config_loader
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(script_dir))
    sys.path.insert(0, os.path.join(project_root, "src"))

    import yaml
    with open(args.config) as f:
        all_configs = yaml.safe_load(f)

    if args.scenario not in all_configs:
        available = [k for k, v in all_configs.items() if isinstance(v, dict)]
        print(f"Error: scenario '{args.scenario}' not found.", file=sys.stderr)
        print(f"Available: {', '.join(available)}", file=sys.stderr)
        sys.exit(1)

    config = all_configs[args.scenario]
    conf_text = generate_telegraf_conf(
        config,
        opcua_endpoint=args.endpoint,
        influxdb_url=args.influxdb_url,
        influxdb_token=args.influxdb_token,
        influxdb_org=args.influxdb_org,
        influxdb_bucket=args.influxdb_bucket,
        run_id=args.run_id,
    )

    if args.output:
        os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
        with open(args.output, "w") as f:
            f.write(conf_text)
        print(f"Generated {args.output} ({conf_text.count('{name=')}"
              f" nodes)", file=sys.stderr)
    else:
        print(conf_text)


if __name__ == "__main__":
    main()
