"""
Historian CSV Analysis Tool

Analyzes event historian CSV files from multi-day simulation runs.
Generates a text summary report and optional matplotlib plots.

Usage:
    python tools/analyze_historian.py <csv_file>
    python tools/analyze_historian.py <csv_file> --plot
    python tools/analyze_historian.py results/historian/  # auto-picks latest file

Requires: pandas (pip install pandas)
Optional: matplotlib (pip install matplotlib) for --plot
"""
import argparse
import os
import sys

try:
    import pandas as pd
except ImportError:
    print("ERROR: pandas is required. Install with: pip install pandas")
    sys.exit(1)

# Ensure tools/ is on the path for report_engine import
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from report_engine import (
    find_latest_csv,
    load_historian_csv,
    run_full_analysis,
    append_run_index,
)


def section(title):
    """Print a section header."""
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}")


def print_report(analysis, csv_path):
    """Format analysis dict as CLI text report."""
    print("Historian Analysis Report")
    print(f"File: {csv_path}")
    print("Generated by: tools/analyze_historian.py")

    # ── 1. Overview ──
    ov = analysis["overview"]
    section("1. OVERVIEW")
    print(f"  Total events:      {ov['total_events']:,}")
    print(f"  Sim time range:    {ov['sim_start']:.0f} - {ov['sim_end']:.0f} ({ov['sim_duration_hrs']:.1f} hours)")
    print(f"  Wall clock:        {ov['wall_start']} -> {ov['wall_end']}")
    print(f"  Events/min (avg):  {ov['events_per_min']:.1f}")
    print("\n  Event type distribution:")
    for etype, info in ov["event_type_distribution"].items():
        print(f"    {etype:25s} {info['count']:>8,}  ({info['pct']:5.1f}%)")
    print("\n  Severity distribution:")
    for sev, count in ov["severity_distribution"].items():
        print(f"    {sev:12s} {count:>8,}")

    # ── 2. Continuity Check ──
    cont = analysis["continuity"]
    section("2. CONTINUITY CHECK")
    print(f"  Production summaries:  {cont['production_summary_count']:,}")
    if "expected_interval_s" in cont:
        print(f"  Summary interval:      {cont['expected_interval_s']:.0f}s (median)")
        if cont["large_gap_count"] > 0:
            print(f"  WARNING: {cont['large_gap_count']} large gaps detected "
                  f"(>{cont['expected_interval_s']*3:.0f}s):")
            for gap in cont.get("large_gaps", []):
                print(f"    t={gap['timestamp']:.0f}  gap={gap['gap_s']:.0f}s")
        else:
            print("  No gaps detected (continuous operation)")
    elif "message" in cont:
        print(f"  {cont['message']}")

    # ── 3. OEE Analysis ──
    oee = analysis["oee"]
    section("3. OEE ANALYSIS (from PRODUCTION_SUMMARY)")
    if oee["sample_count"] > 0:
        print(f"  Line OEE samples:  {oee['sample_count']:,}")
        print(f"  Mean:              {oee['mean']:.4f}")
        print(f"  Median:            {oee['median']:.4f}")
        print(f"  Std:               {oee['std']:.4f}")
        print(f"  Min:               {oee['min']:.4f}  at t={oee['min_timestamp']:.0f}")
        print(f"  Max:               {oee['max']:.4f}  at t={oee['max_timestamp']:.0f}")

        if "unchanged_between_summaries" in oee:
            print("\n  OEE stability (bucket check):")
            print(f"    Unchanged between summaries: {oee['unchanged_between_summaries']:,} ({oee['unchanged_pct']:.1f}%)")
            print(f"    Changed between summaries:   {oee['changed_between_summaries']:,} ({100-oee['unchanged_pct']:.1f}%)")
            status = oee.get("stability_status", "?")
            if status == "PASS":
                print("    PASS: OEE is stable (bucketed behavior confirmed)")
            elif status == "WARN":
                print("    WARN: OEE is moderately stable")
            else:
                print("    FAIL: OEE changes too frequently (bucketing may not be working)")

        print(f"\n  OEE = 1.0 spikes:  {oee['spikes_to_1']} ({oee['spikes_to_1_pct']:.1f}%)")
        spike = oee.get("spike_status", "?")
        if spike == "PASS":
            print("    PASS: No unrealistic 100% OEE spikes")
        elif spike == "OK":
            print("    OK: Very few spikes (< 1%)")
        else:
            print("    WARN: Significant 100% OEE occurrences")
    elif "message" in oee:
        print(f"  {oee['message']}")

    # ── 4. Per-Machine OEE ──
    moee = analysis["machine_oee"]
    section("4. PER-MACHINE OEE (from STATE_CHANGE events)")
    for m, data in moee["machines"].items():
        if "oee_mean" in data:
            print(f"\n  {m}:")
            print(f"    OEE: mean={data['oee_mean']:.4f} median={data['oee_median']:.4f} "
                  f"std={data['oee_std']:.4f} min={data['oee_min']:.4f} max={data['oee_max']:.4f}")
            print(f"    Utilisation: mean={data['utilisation_mean']:.4f}")
            print(f"    Last event: t={data['last_timestamp']:.0f} "
                  f"partcount={data['last_partcount']} "
                  f"good={data['last_good_parts']} defective={data['last_defective_parts']}")

    # ── 5. Failure Analysis ──
    fail = analysis["failures"]
    section("5. FAILURE ANALYSIS")
    for m, data in fail["machines"].items():
        print(f"\n  {m}:")
        print(f"    Failure events:  {data['failure_count']}")
        print(f"    Repair events:   {data['repair_count']}")
        if "mttf_mean" in data:
            print(f"    Avg time between failures: {data['mttf_mean']:.0f}s "
                  f"(median: {data['mttf_median']:.0f}s)")
        if "mttr_mean" in data:
            print(f"    Avg repair time: {data['mttr_mean']:.1f}s "
                  f"(median: {data['mttr_median']:.1f}s)")

    # ── 6. Quality Routing ──
    qr = analysis["quality_routing"]
    section("6. QUALITY ROUTING")
    print(f"  Total SCRAP events:  {qr['total_scrap_events']}")
    print(f"  Total REWORK events: {qr['total_rework_events']}")
    for m, data in qr["machines"].items():
        print(f"\n  {m}:")
        print(f"    Scrap events: {data['scrap_events']}  "
              f"(final count: {data.get('final_scrap_count', '?')})")
        if data.get("rework_events", 0) > 0:
            print(f"    Rework events: {data['rework_events']}  "
                  f"(total: {data.get('final_rework_count', '?')}, "
                  f"success: {data.get('rework_success_count', '?')})")
            if "rework_success_rate" in data:
                print(f"    Rework success rate: {data['rework_success_rate']:.1%}")

    # ── 7. Shift Analysis ──
    sh = analysis["shifts"]
    section("7. SHIFT ANALYSIS")
    if sh["shift_change_count"] > 0:
        print(f"  Shift changes:     {sh['shift_change_count']}")
        for s in sh["shifts"]:
            print(f"    t={s['timestamp']:.0f}: Shift {s['shift_number']} "
                  f"({s['shift_name']}) started "
                  f"[prev: {s['prev_shift_name']}, parts={s['prev_shift_parts']}, "
                  f"OEE={s['prev_shift_oee']}]")
    else:
        print("  No shift changes recorded")

    # ── 8. Buffer Dynamics ──
    buf = analysis["buffer_dynamics"]
    section("8. BUFFER DYNAMICS")
    for b, data in buf["buffers"].items():
        if "level_mean" in data:
            print(f"\n  {b}: {data['event_count']} level changes")
            print(f"    Level: mean={data['level_mean']:.1f} min={data['level_min']} "
                  f"max={data['level_max']} std={data['level_std']:.1f}")
            print(f"    Full: {data['full_pct']:.1f}%  Empty: {data['empty_pct']:.1f}%")

    # ── 9. Throughput ──
    tp = analysis["throughput"]
    section("9. THROUGHPUT")
    if "total_parts" in tp:
        print(f"  Total parts:       {tp['total_parts']:,}")
        print(f"  Sim time elapsed:  {tp['elapsed_s']:.0f}s ({tp['elapsed_hrs']:.1f}h)")
        print(f"  Throughput:        {tp['ppm']:.2f} parts/min")
        print("  Expected (PPM=60): 60.00 parts/min")
        print(f"  Efficiency:        {tp['efficiency_pct']:.1f}%")
    elif "message" in tp:
        print(f"  {tp['message']}")

    # ── 10. Anomaly Check ──
    anom = analysis["anomalies"]
    section("10. ANOMALY CHECK")
    for check in anom["checks"]:
        if check["status"] == "FAIL":
            print(f"  WARNING: {check['message']}")
    if anom["anomaly_count"] == 0:
        print("  All checks passed - no anomalies detected")

    print(f"\n{'='*60}")
    print("  END OF REPORT")
    print(f"{'='*60}")


def print_validation(validation):
    """Format validation dict as CLI text report."""
    section("11. CSV vs INFLUXDB (Telegraf OPC UA) COMPARISON")

    print("  Telegraf data range:")
    print(f"    Points received:    {validation['telegraf_total_points']:,}")

    first_st = validation.get("telegraf_first_simtime")
    last_st = validation.get("telegraf_last_simtime")
    if first_st is not None and last_st is not None:
        span_hrs = (last_st - first_st) / 3600
        print(f"    Time span:          {first_st} - {last_st} ({span_hrs:.1f} hours)")

    print("\n  Validation checks:")
    for check in validation["checks"]:
        status_str = check["status"]
        print(f"    {check['name']:25s} CSV={check['csv_value']:>12s}  "
              f"Telegraf={check['telegraf_value']:>12s}  {status_str}")

    print("\n  Pipeline verdict: ", end="")
    if validation["verdict"] == "PASS":
        print(f"ALL CHECKS PASSED ({validation['passed']}/{validation['total']})")
    else:
        print(f"SOME CHECKS FAILED ({validation['passed']}/{validation['total']})")


def plot_analysis(df, analysis, csv_path):
    """Generate matplotlib plots."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("\nWARNING: matplotlib not installed, skipping plots. "
              "Install with: pip install matplotlib")
        return

    fig, axes = plt.subplots(3, 2, figsize=(16, 12))
    fig.suptitle(f"Historian Analysis: {os.path.basename(csv_path)}", fontsize=14)

    prod_summaries = df[df["event_type"] == "PRODUCTION_SUMMARY"].copy()
    from report_engine import parse_extra_json
    if len(prod_summaries) > 0:
        extras = parse_extra_json(prod_summaries["extra_json"])
        prod_summaries["line_oee"] = extras.apply(lambda x: x.get("line_oee", None))
        prod_summaries["line_oee"] = pd.to_numeric(prod_summaries["line_oee"], errors="coerce")

    # 1. Line OEE over time
    ax = axes[0, 0]
    if len(prod_summaries) > 0 and "line_oee" in prod_summaries.columns:
        valid = prod_summaries[prod_summaries["line_oee"].notna()]
        ax.plot(valid["timestamp"] / 3600, valid["line_oee"], linewidth=0.5)
        ax.set_ylabel("Line OEE")
        ax.set_xlabel("Sim time (hours)")
        ax.set_title("Line OEE Over Time")
        ax.set_ylim(0, 1.05)
        ax.grid(True, alpha=0.3)

    # 2. Throughput over time
    ax = axes[0, 1]
    if len(prod_summaries) > 1:
        ax.plot(prod_summaries["timestamp"] / 3600, prod_summaries["partcount"], linewidth=0.5)
        ax.set_ylabel("Total parts")
        ax.set_xlabel("Sim time (hours)")
        ax.set_title("Cumulative Throughput")
        ax.grid(True, alpha=0.3)

    # 3. Per-machine OEE
    ax = axes[1, 0]
    machine_sc = df[(df["source_type"] == "machine") & (df["event_type"] == "STATE_CHANGE")]
    for m in sorted(machine_sc["source"].unique()):
        m_data = machine_sc[machine_sc["source"] == m]
        ax.plot(m_data["timestamp"] / 3600, m_data["oee"], label=m, linewidth=0.3, alpha=0.7)
    ax.set_ylabel("Machine OEE")
    ax.set_xlabel("Sim time (hours)")
    ax.set_title("Per-Machine OEE")
    ax.set_ylim(0, 1.05)
    ax.legend()
    ax.grid(True, alpha=0.3)

    # 4. Buffer level
    ax = axes[1, 1]
    buf_events = df[(df["source_type"] == "buffer") & (df["event_type"] == "STATE_CHANGE")]
    for b in sorted(buf_events["source"].unique()):
        b_data = buf_events[buf_events["source"] == b]
        ax.plot(b_data["timestamp"] / 3600, b_data["buffer_level"], label=b, linewidth=0.3, alpha=0.7)
    ax.set_ylabel("Buffer level")
    ax.set_xlabel("Sim time (hours)")
    ax.set_title("Buffer Levels Over Time")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # 5. Event rate over time
    ax = axes[2, 0]
    bucket_size = 600
    df_copy = df.copy()
    df_copy["bucket"] = (df_copy["timestamp"] / bucket_size).astype(int) * bucket_size
    event_rate = df_copy.groupby("bucket").size()
    ax.bar(event_rate.index / 3600, event_rate.values, width=bucket_size / 3600 * 0.8, alpha=0.7)
    ax.set_ylabel("Events per 10 min")
    ax.set_xlabel("Sim time (hours)")
    ax.set_title("Event Rate Over Time")
    ax.grid(True, alpha=0.3)

    # 6. Machine state distribution
    ax = axes[2, 1]
    state_changes = df[(df["event_type"] == "STATE_CHANGE") & (df["source_type"] == "machine")]
    if len(state_changes) > 0:
        state_counts = state_changes.groupby(["source", "new_state"]).size().unstack(fill_value=0)
        state_counts.plot(kind="bar", stacked=True, ax=ax, alpha=0.8)
        ax.set_ylabel("State transitions")
        ax.set_title("Machine State Transition Counts")
        ax.tick_params(axis='x', rotation=0)
        ax.legend(fontsize=7, loc="upper right")

    plt.tight_layout()
    output_path = csv_path.replace(".csv", "_analysis.png")
    plt.savefig(output_path, dpi=150)
    print(f"\nPlots saved to: {output_path}")
    plt.close()


def query_influxdb_telegraf(influx_url, influx_token, influx_org, influx_bucket,
                            run_id=None, time_start=None, time_end=None):
    """Query Telegraf-sourced OPC UA data from InfluxDB.

    Args:
        influx_url: InfluxDB URL
        influx_token: InfluxDB authentication token
        influx_org: InfluxDB organization
        influx_bucket: InfluxDB bucket name
        run_id: Optional run_id tag to scope queries to a specific run
        time_start: Optional ISO 8601 start time (from CSV wall_clock)
        time_end: Optional ISO 8601 end time (from CSV wall_clock)

    Returns a dict with data point count, time range, throughput, OEE values,
    per-machine partcounts, and update rate statistics.
    """
    try:
        from influxdb_client import InfluxDBClient
    except ImportError:
        raise ImportError("influxdb-client is required. "
                          "Install with: pip install influxdb-client")

    client = InfluxDBClient(url=influx_url, token=influx_token, org=influx_org,
                            timeout=60_000)
    query_api = client.query_api()

    # Build time range clause
    # Flux requires RFC 3339 timestamps (with Z suffix) in range()
    if time_start and time_end:
        # Ensure timestamps end with Z for Flux compatibility
        ts = time_start.rstrip("Z") + "Z"
        te = time_end.rstrip("Z") + "Z"
        range_clause = f'range(start: {ts}, stop: {te})'
    else:
        range_clause = 'range(start: -30d)'

    # Build optional run_id filter
    run_id_filter = ""
    if run_id:
        run_id_filter = f'\n      |> filter(fn: (r) => r.run_id == "{run_id}")'

    result = {}

    # 1. Data point count
    flux = f'''
    from(bucket: "{influx_bucket}")
      |> {range_clause}
      |> filter(fn: (r) => r._measurement == "opcua"){run_id_filter}
      |> count()
      |> group()
      |> sum()
    '''
    tables = query_api.query(flux, org=influx_org)
    total_points = 0
    for table in tables:
        for record in table.records:
            total_points += record.get_value()
    result["total_points"] = total_points

    # 2. Time range
    for label, agg in [("first", "first"), ("last", "last")]:
        flux_q = f'''
        from(bucket: "{influx_bucket}")
          |> {range_clause}
          |> filter(fn: (r) => r._measurement == "opcua"){run_id_filter}
          |> filter(fn: (r) => r._field == "SimTime")
          |> {agg}()
        '''
        tables = query_api.query(flux_q, org=influx_org)
        val = None
        for table in tables:
            for record in table.records:
                val = record.get_value()
        result[f"{label}_simtime"] = val

    # 3. Final throughput
    flux_tp = f'''
    from(bucket: "{influx_bucket}")
      |> {range_clause}
      |> filter(fn: (r) => r._measurement == "opcua"){run_id_filter}
      |> filter(fn: (r) => r._field == "Throughput")
      |> last()
    '''
    tables = query_api.query(flux_tp, org=influx_org)
    final_throughput = None
    for table in tables:
        for record in table.records:
            final_throughput = record.get_value()
    result["final_throughput"] = final_throughput

    # 4. Line OEE over time
    flux_oee = f'''
    from(bucket: "{influx_bucket}")
      |> {range_clause}
      |> filter(fn: (r) => r._measurement == "opcua"){run_id_filter}
      |> filter(fn: (r) => r._field == "LineOEE")
      |> sort(columns: ["_time"])
    '''
    tables = query_api.query(flux_oee, org=influx_org)
    oee_values = []
    for table in tables:
        for record in table.records:
            oee_values.append({
                "time": record.get_time(),
                "value": record.get_value(),
            })
    result["oee_timeseries"] = oee_values

    # 5. Per-machine partcounts
    # Field names are prefixed: M1_PartCount, M2_PartCount, etc.
    flux_parts = f'''
    from(bucket: "{influx_bucket}")
      |> {range_clause}
      |> filter(fn: (r) => r._measurement == "opcua"){run_id_filter}
      |> filter(fn: (r) => r._field =~ /_PartCount$/)
      |> filter(fn: (r) => r.source_type == "machine")
      |> last()
    '''
    tables = query_api.query(flux_parts, org=influx_org)
    machine_partcounts = {}
    for table in tables:
        for record in table.records:
            source = record.values.get("source", "unknown")
            machine_partcounts[source] = record.get_value()
    result["machine_partcounts"] = machine_partcounts

    # 6. Buffer levels
    # Field names are prefixed: B1_Level, B2_Level, etc.
    flux_buf = f'''
    from(bucket: "{influx_bucket}")
      |> {range_clause}
      |> filter(fn: (r) => r._measurement == "opcua"){run_id_filter}
      |> filter(fn: (r) => r._field =~ /_Level$/)
      |> filter(fn: (r) => r.source_type == "buffer")
      |> last()
    '''
    tables = query_api.query(flux_buf, org=influx_org)
    buffer_levels = {}
    for table in tables:
        for record in table.records:
            source = record.values.get("source", "unknown")
            buffer_levels[source] = record.get_value()
    result["buffer_levels"] = buffer_levels

    # 7. Update rate
    flux_rate = f'''
    from(bucket: "{influx_bucket}")
      |> {range_clause}
      |> filter(fn: (r) => r._measurement == "opcua"){run_id_filter}
      |> filter(fn: (r) => r._field == "SimTime")
      |> sort(columns: ["_time"])
      |> elapsed(unit: 1s)
    '''
    tables = query_api.query(flux_rate, org=influx_org)
    intervals = []
    for table in tables:
        for record in table.records:
            elapsed_val = record.values.get("elapsed", None)
            if elapsed_val is not None and elapsed_val > 0:
                intervals.append(elapsed_val)
    result["update_intervals"] = intervals
    result["avg_update_rate"] = (sum(intervals) / len(intervals)) if intervals else None

    # 8. Data gaps
    gaps = [i for i in intervals if i > 5]
    result["gaps_over_5s"] = len(gaps)

    client.close()
    return result


def main():
    parser = argparse.ArgumentParser(description="Analyze historian CSV files")
    parser.add_argument("path", help="CSV file path or directory (auto-picks latest)")
    parser.add_argument("--plot", action="store_true", help="Generate matplotlib plots")
    parser.add_argument("--influxdb", action="store_true",
                        help="Enable InfluxDB comparison (Telegraf-sourced data)")
    parser.add_argument("--influxdb-url", default=None,
                        help="InfluxDB URL (default: env INFLUXDB_URL or http://localhost:8086)")
    parser.add_argument("--influxdb-token", default=None,
                        help="InfluxDB token (default: env INFLUXDB_TOKEN)")
    parser.add_argument("--influxdb-org", default=None,
                        help="InfluxDB org (default: env INFLUXDB_ORG or 'simantha')")
    parser.add_argument("--influxdb-bucket", default=None,
                        help="InfluxDB bucket (default: env INFLUXDB_BUCKET or 'manufacturing')")
    parser.add_argument("--run-id", default=None,
                        help="Run ID to scope InfluxDB queries (default: auto-detect from CSV)")
    args = parser.parse_args()

    # Resolve path
    if os.path.isdir(args.path):
        csv_path = find_latest_csv(args.path)
        if csv_path is None:
            print(f"No historian CSV files found in {args.path}")
            sys.exit(1)
        print(f"Auto-selected latest file: {csv_path}")
    else:
        csv_path = args.path

    if not os.path.exists(csv_path):
        print(f"File not found: {csv_path}")
        sys.exit(1)

    # Load and analyze
    print(f"Loading {csv_path}...")
    df = load_historian_csv(csv_path)
    analysis = run_full_analysis(df)
    print_report(analysis, csv_path)

    # Auto-append to run index
    append_run_index(csv_path, analysis)

    if args.plot:
        plot_analysis(df, analysis, csv_path)

    # InfluxDB comparison (Telegraf OPC UA pipeline validation)
    if args.influxdb:
        influx_url = (args.influxdb_url
                      or os.environ.get("INFLUXDB_URL", "http://localhost:8086"))
        influx_token = (args.influxdb_token
                        or os.environ.get("INFLUXDB_TOKEN"))
        influx_org = (args.influxdb_org
                      or os.environ.get("INFLUXDB_ORG", "simantha"))
        influx_bucket = (args.influxdb_bucket
                         or os.environ.get("INFLUXDB_BUCKET", "manufacturing"))

        if not influx_token:
            print("\nERROR: --influxdb-token or INFLUXDB_TOKEN env var is required")
            sys.exit(1)

        # Extract run_id and time range from CSV for scoped queries
        csv_run_id = args.run_id
        time_start = None
        time_end = None
        if csv_run_id is None and "run_id" in df.columns and len(df) > 0:
            first_rid = df["run_id"].iloc[0]
            if pd.notna(first_rid) and str(first_rid).strip():
                csv_run_id = str(first_rid).strip()
        if "wall_clock" in df.columns and len(df) > 0:
            time_start = str(df["wall_clock"].iloc[0])
            time_end = str(df["wall_clock"].iloc[-1])

        scope_info = []
        if csv_run_id:
            scope_info.append(f"run_id={csv_run_id}")
        if time_start:
            scope_info.append(f"time={time_start}..{time_end}")
        scope_str = f" (scoped: {', '.join(scope_info)})" if scope_info else ""

        print(f"\nQuerying InfluxDB at {influx_url}{scope_str} ...")
        try:
            influx_data = query_influxdb_telegraf(
                influx_url, influx_token, influx_org, influx_bucket,
                run_id=csv_run_id, time_start=time_start, time_end=time_end,
            )
        except ImportError as e:
            print(f"ERROR: {e}")
            sys.exit(1)

        from report_engine import validate_pipeline
        validation = validate_pipeline(df, influx_data)
        print_validation(validation)


if __name__ == "__main__":
    main()
