"""
Historian CSV Analysis Tool

Analyzes event historian CSV files from multi-day simulation runs.
Generates a text summary report and optional matplotlib plots.

Usage:
    python tools/analyze_historian.py <csv_file>
    python tools/analyze_historian.py <csv_file> --plot
    python tools/analyze_historian.py results/historian/  # auto-picks latest file

Requires: pandas (pip install pandas)
Optional: matplotlib (pip install matplotlib) for --plot
"""
import argparse
import json
import os
import sys
from pathlib import Path

try:
    import pandas as pd
except ImportError:
    print("ERROR: pandas is required. Install with: pip install pandas")
    sys.exit(1)


def find_latest_csv(directory):
    """Find the most recent historian CSV file in a directory."""
    csvs = sorted(Path(directory).glob("*_events*.csv"), key=os.path.getmtime)
    if not csvs:
        print(f"No historian CSV files found in {directory}")
        sys.exit(1)
    return str(csvs[-1])


def load_csv(path):
    """Load historian CSV with appropriate dtypes."""
    df = pd.read_csv(path, dtype={
        "timestamp": float,
        "event_type": str,
        "source": str,
        "source_type": str,
        "severity": str,
        "message": str,
        "old_state": str,
        "new_state": str,
        "partcount": "Int64",
        "good_parts": "Int64",
        "defective_parts": "Int64",
        "buffer_level": "Int64",
        "oee": float,
        "utilisation": float,
        "shift_number": "Int64",
        "shift_name": str,
        "extra_json": str,
    })
    return df


def parse_extra_json(series):
    """Parse extra_json column into dicts, handling NaN/empty."""
    def _parse(val):
        if pd.isna(val) or val == "":
            return {}
        try:
            return json.loads(val)
        except (json.JSONDecodeError, TypeError):
            return {}
    return series.apply(_parse)


def section(title):
    """Print a section header."""
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}")


def analyze(df, csv_path):
    """Run all analyses and print report."""
    print(f"Historian Analysis Report")
    print(f"File: {csv_path}")
    print(f"Generated by: tools/analyze_historian.py")

    # ── 1. Overview ──
    section("1. OVERVIEW")
    sim_start = df["timestamp"].min()
    sim_end = df["timestamp"].max()
    sim_duration_hrs = (sim_end - sim_start) / 3600
    wall_start = df["wall_clock"].iloc[0] if "wall_clock" in df.columns else "N/A"
    wall_end = df["wall_clock"].iloc[-1] if "wall_clock" in df.columns else "N/A"

    print(f"  Total events:      {len(df):,}")
    print(f"  Sim time range:    {sim_start:.0f} - {sim_end:.0f} ({sim_duration_hrs:.1f} hours)")
    print(f"  Wall clock:        {wall_start} -> {wall_end}")
    print(f"  Events/min (avg):  {len(df) / max(sim_duration_hrs * 60, 1):.1f}")

    # Event type breakdown
    print(f"\n  Event type distribution:")
    for etype, count in df["event_type"].value_counts().items():
        print(f"    {etype:25s} {count:>8,}  ({100*count/len(df):5.1f}%)")

    # Severity breakdown
    print(f"\n  Severity distribution:")
    for sev, count in df["severity"].value_counts().items():
        print(f"    {sev:12s} {count:>8,}")

    # ── 2. Continuity Check ──
    section("2. CONTINUITY CHECK")
    prod_summaries = df[df["event_type"] == "PRODUCTION_SUMMARY"].copy()
    if len(prod_summaries) > 1:
        gaps = prod_summaries["timestamp"].diff()
        expected_interval = gaps.median()
        large_gaps = gaps[gaps > expected_interval * 3].dropna()
        print(f"  Production summaries:  {len(prod_summaries):,}")
        print(f"  Summary interval:      {expected_interval:.0f}s (median)")
        if len(large_gaps) > 0:
            print(f"  WARNING: {len(large_gaps)} large gaps detected (>{expected_interval*3:.0f}s):")
            for idx in large_gaps.index[:5]:
                row = prod_summaries.loc[idx]
                print(f"    t={row['timestamp']:.0f}  gap={gaps.loc[idx]:.0f}s")
        else:
            print(f"  No gaps detected (continuous operation)")
    else:
        print(f"  Too few production summaries ({len(prod_summaries)}) to check continuity")

    # ── 3. OEE Analysis ──
    section("3. OEE ANALYSIS (from PRODUCTION_SUMMARY)")
    if len(prod_summaries) > 0:
        extras = parse_extra_json(prod_summaries["extra_json"])
        prod_summaries = prod_summaries.copy()
        prod_summaries["line_oee"] = extras.apply(lambda x: x.get("line_oee", None))
        prod_summaries["line_oee"] = pd.to_numeric(prod_summaries["line_oee"], errors="coerce")

        valid_oee = prod_summaries["line_oee"].dropna()
        if len(valid_oee) > 0:
            print(f"  Line OEE samples:  {len(valid_oee):,}")
            print(f"  Mean:              {valid_oee.mean():.4f}")
            print(f"  Median:            {valid_oee.median():.4f}")
            print(f"  Std:               {valid_oee.std():.4f}")
            print(f"  Min:               {valid_oee.min():.4f}  at t={prod_summaries.loc[valid_oee.idxmin(), 'timestamp']:.0f}")
            print(f"  Max:               {valid_oee.max():.4f}  at t={prod_summaries.loc[valid_oee.idxmax(), 'timestamp']:.0f}")

            # Check for erratic behavior (OEE bucket should produce step-changes)
            oee_changes = valid_oee.diff().abs().dropna()
            if len(oee_changes) > 0:
                # Count how many summaries show the SAME OEE as previous
                # (should be ~9 out of 10 if bucket=600s and summary=60s)
                unchanged = (oee_changes < 0.0001).sum()
                changed = (oee_changes >= 0.0001).sum()
                print(f"\n  OEE stability (bucket check):")
                print(f"    Unchanged between summaries: {unchanged:,} ({100*unchanged/len(oee_changes):.1f}%)")
                print(f"    Changed between summaries:   {changed:,} ({100*changed/len(oee_changes):.1f}%)")
                if unchanged / max(len(oee_changes), 1) > 0.8:
                    print(f"    PASS: OEE is stable (bucketed behavior confirmed)")
                elif unchanged / max(len(oee_changes), 1) > 0.5:
                    print(f"    WARN: OEE is moderately stable")
                else:
                    print(f"    FAIL: OEE changes too frequently (bucketing may not be working)")

            # OEE spikes to 1.0 check
            spikes = (valid_oee >= 0.999).sum()
            print(f"\n  OEE = 1.0 spikes:  {spikes} ({100*spikes/len(valid_oee):.1f}%)")
            if spikes == 0:
                print(f"    PASS: No unrealistic 100% OEE spikes")
            elif spikes < len(valid_oee) * 0.01:
                print(f"    OK: Very few spikes (< 1%)")
            else:
                print(f"    WARN: Significant 100% OEE occurrences")
        else:
            print(f"  No line_oee data found in extra_json")

    # ── 4. Per-Machine OEE ──
    section("4. PER-MACHINE OEE (from STATE_CHANGE events)")
    machine_events = df[(df["source_type"] == "machine") & (df["event_type"] == "STATE_CHANGE")]
    machines = sorted(machine_events["source"].unique())
    for m in machines:
        m_events = machine_events[machine_events["source"] == m]
        m_oee = m_events["oee"].dropna()
        if len(m_oee) > 0:
            print(f"\n  {m}:")
            print(f"    OEE: mean={m_oee.mean():.4f} median={m_oee.median():.4f} "
                  f"std={m_oee.std():.4f} min={m_oee.min():.4f} max={m_oee.max():.4f}")
            print(f"    Utilisation: mean={m_events['utilisation'].mean():.4f}")
            last_event = m_events.iloc[-1]
            print(f"    Last event: t={last_event['timestamp']:.0f} "
                  f"partcount={last_event['partcount']} "
                  f"good={last_event['good_parts']} defective={last_event['defective_parts']}")

    # ── 5. Failure Analysis ──
    section("5. FAILURE ANALYSIS")
    failures = df[(df["event_type"] == "STATE_CHANGE") &
                  (df["new_state"].isin(["FAILED", "UNDER_REPAIR"]))]
    repairs = df[(df["event_type"] == "STATE_CHANGE") &
                 (df["old_state"].isin(["FAILED", "UNDER_REPAIR"])) &
                 (~df["new_state"].isin(["FAILED", "UNDER_REPAIR"]))]

    for m in machines:
        m_failures = failures[failures["source"] == m]
        m_repairs = repairs[repairs["source"] == m]
        print(f"\n  {m}:")
        print(f"    Failure events:  {len(m_failures)}")
        print(f"    Repair events:   {len(m_repairs)}")

        if len(m_failures) > 1:
            fail_times = m_failures["timestamp"].values
            tbf = [fail_times[i+1] - fail_times[i] for i in range(len(fail_times)-1)]
            if tbf:
                import statistics
                print(f"    Avg time between failures: {statistics.mean(tbf):.0f}s "
                      f"(median: {statistics.median(tbf):.0f}s)")

        if len(m_failures) > 0 and len(m_repairs) > 0:
            # Pair failures with next repair
            repair_durations = []
            repair_times = sorted(m_repairs["timestamp"].values)
            for ft in m_failures["timestamp"].values:
                # Find next repair after this failure
                later_repairs = [rt for rt in repair_times if rt > ft]
                if later_repairs:
                    repair_durations.append(later_repairs[0] - ft)
            if repair_durations:
                import statistics
                print(f"    Avg repair time: {statistics.mean(repair_durations):.1f}s "
                      f"(median: {statistics.median(repair_durations):.1f}s)")

    # ── 6. Quality / Scrap / Rework ──
    section("6. QUALITY ROUTING")
    scraps = df[df["event_type"] == "SCRAP"]
    reworks = df[df["event_type"] == "REWORK"]
    print(f"  Total SCRAP events:  {len(scraps)}")
    print(f"  Total REWORK events: {len(reworks)}")

    for m in machines:
        m_scraps = scraps[scraps["source"] == m]
        m_reworks = reworks[reworks["source"] == m]
        if len(m_scraps) > 0 or len(m_reworks) > 0:
            # Get final scrap/rework counts from extra_json
            last_scrap_extra = {}
            if len(m_scraps) > 0:
                last_scrap_extra = parse_extra_json(m_scraps.iloc[-1:]["extra_json"]).iloc[0]
            last_rework_extra = {}
            if len(m_reworks) > 0:
                last_rework_extra = parse_extra_json(m_reworks.iloc[-1:]["extra_json"]).iloc[0]

            print(f"\n  {m}:")
            print(f"    Scrap events: {len(m_scraps)}  "
                  f"(final count: {last_scrap_extra.get('scrap_count', '?')})")
            if len(m_reworks) > 0:
                rework_total = last_rework_extra.get("rework_count", "?")
                rework_success = last_rework_extra.get("rework_success_count", "?")
                print(f"    Rework events: {len(m_reworks)}  "
                      f"(total: {rework_total}, success: {rework_success})")
                if isinstance(rework_total, (int, float)) and rework_total > 0:
                    rate = rework_success / rework_total if isinstance(rework_success, (int, float)) else 0
                    print(f"    Rework success rate: {rate:.1%}")

    # ── 7. Shift Analysis ──
    section("7. SHIFT ANALYSIS")
    shifts = df[df["event_type"] == "SHIFT_CHANGE"]
    if len(shifts) > 0:
        print(f"  Shift changes:     {len(shifts)}")
        shift_extras = parse_extra_json(shifts["extra_json"])
        for _, row in shifts.iterrows():
            extra = shift_extras.loc[row.name]
            prev_name = extra.get("prev_shift_name", "?")
            prev_parts = extra.get("prev_shift_parts", "?")
            prev_oee = extra.get("prev_shift_oee", "?")
            print(f"    t={row['timestamp']:.0f}: Shift {row['shift_number']} "
                  f"({row['shift_name']}) started "
                  f"[prev: {prev_name}, parts={prev_parts}, OEE={prev_oee}]")
    else:
        print(f"  No shift changes recorded")

    # ── 8. Buffer Dynamics ──
    section("8. BUFFER DYNAMICS")
    buf_events = df[(df["source_type"] == "buffer") & (df["event_type"] == "STATE_CHANGE")]
    buffers = sorted(buf_events["source"].unique())
    for b in buffers:
        b_events = buf_events[buf_events["source"] == b]
        levels = b_events["buffer_level"].dropna()
        if len(levels) > 0:
            print(f"\n  {b}: {len(b_events)} level changes")
            print(f"    Level: mean={levels.mean():.1f} min={levels.min()} "
                  f"max={levels.max()} std={levels.std():.1f}")
            full_pct = (levels == levels.max()).sum() / len(levels) * 100
            empty_pct = (levels == 0).sum() / len(levels) * 100
            print(f"    Full: {full_pct:.1f}%  Empty: {empty_pct:.1f}%")

    # ── 9. Throughput ──
    section("9. THROUGHPUT")
    if len(prod_summaries) > 1:
        first = prod_summaries.iloc[0]
        last = prod_summaries.iloc[-1]
        elapsed = last["timestamp"] - first["timestamp"]
        parts = last["partcount"] - first["partcount"]
        if elapsed > 0:
            ppm = parts / (elapsed / 60)
            print(f"  Total parts:       {last['partcount']:,}")
            print(f"  Sim time elapsed:  {elapsed:.0f}s ({elapsed/3600:.1f}h)")
            print(f"  Throughput:        {ppm:.2f} parts/min")
            print(f"  Expected (PPM=60): {60:.2f} parts/min")
            print(f"  Efficiency:        {ppm/60*100:.1f}%")

    # ── 10. Anomalies ──
    section("10. ANOMALY CHECK")
    anomalies = 0

    # Check for negative partcounts
    neg_parts = df[df["partcount"] < 0] if "partcount" in df.columns else pd.DataFrame()
    if len(neg_parts) > 0:
        print(f"  WARNING: {len(neg_parts)} events with negative partcount")
        anomalies += 1

    # Check for OEE > 1.0
    high_oee = df[df["oee"] > 1.001] if "oee" in df.columns else pd.DataFrame()
    if len(high_oee) > 0:
        print(f"  WARNING: {len(high_oee)} events with OEE > 1.0")
        anomalies += 1

    # Check for timestamps going backwards
    ts_diff = df["timestamp"].diff()
    backwards = (ts_diff < 0).sum()
    if backwards > 0:
        print(f"  WARNING: {backwards} timestamps go backwards")
        anomalies += 1

    # Check for missing event types we expect
    expected_types = {"STATE_CHANGE", "PRODUCTION_SUMMARY"}
    missing = expected_types - set(df["event_type"].unique())
    if missing:
        print(f"  WARNING: Missing expected event types: {missing}")
        anomalies += 1

    if anomalies == 0:
        print(f"  All checks passed - no anomalies detected")

    print(f"\n{'='*60}")
    print(f"  END OF REPORT")
    print(f"{'='*60}")

    return prod_summaries


def plot_analysis(df, prod_summaries, csv_path):
    """Generate matplotlib plots."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("\nWARNING: matplotlib not installed, skipping plots. Install with: pip install matplotlib")
        return

    fig, axes = plt.subplots(3, 2, figsize=(16, 12))
    fig.suptitle(f"Historian Analysis: {os.path.basename(csv_path)}", fontsize=14)

    # 1. Line OEE over time
    ax = axes[0, 0]
    if len(prod_summaries) > 0 and "line_oee" in prod_summaries.columns:
        valid = prod_summaries[prod_summaries["line_oee"].notna()]
        ax.plot(valid["timestamp"] / 3600, valid["line_oee"], linewidth=0.5)
        ax.set_ylabel("Line OEE")
        ax.set_xlabel("Sim time (hours)")
        ax.set_title("Line OEE Over Time")
        ax.set_ylim(0, 1.05)
        ax.grid(True, alpha=0.3)

    # 2. Throughput over time
    ax = axes[0, 1]
    if len(prod_summaries) > 1:
        ax.plot(prod_summaries["timestamp"] / 3600, prod_summaries["partcount"], linewidth=0.5)
        ax.set_ylabel("Total parts")
        ax.set_xlabel("Sim time (hours)")
        ax.set_title("Cumulative Throughput")
        ax.grid(True, alpha=0.3)

    # 3. Per-machine OEE
    ax = axes[1, 0]
    machine_sc = df[(df["source_type"] == "machine") & (df["event_type"] == "STATE_CHANGE")]
    for m in sorted(machine_sc["source"].unique()):
        m_data = machine_sc[machine_sc["source"] == m]
        ax.plot(m_data["timestamp"] / 3600, m_data["oee"], label=m, linewidth=0.3, alpha=0.7)
    ax.set_ylabel("Machine OEE")
    ax.set_xlabel("Sim time (hours)")
    ax.set_title("Per-Machine OEE")
    ax.set_ylim(0, 1.05)
    ax.legend()
    ax.grid(True, alpha=0.3)

    # 4. Buffer level
    ax = axes[1, 1]
    buf_events = df[(df["source_type"] == "buffer") & (df["event_type"] == "STATE_CHANGE")]
    for b in sorted(buf_events["source"].unique()):
        b_data = buf_events[buf_events["source"] == b]
        ax.plot(b_data["timestamp"] / 3600, b_data["buffer_level"], label=b, linewidth=0.3, alpha=0.7)
    ax.set_ylabel("Buffer level")
    ax.set_xlabel("Sim time (hours)")
    ax.set_title("Buffer Levels Over Time")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # 5. Event rate over time (events per 10-min bucket)
    ax = axes[2, 0]
    bucket_size = 600  # 10 minutes
    df_copy = df.copy()
    df_copy["bucket"] = (df_copy["timestamp"] / bucket_size).astype(int) * bucket_size
    event_rate = df_copy.groupby("bucket").size()
    ax.bar(event_rate.index / 3600, event_rate.values, width=bucket_size/3600*0.8, alpha=0.7)
    ax.set_ylabel("Events per 10 min")
    ax.set_xlabel("Sim time (hours)")
    ax.set_title("Event Rate Over Time")
    ax.grid(True, alpha=0.3)

    # 6. Machine state distribution
    ax = axes[2, 1]
    state_changes = df[(df["event_type"] == "STATE_CHANGE") & (df["source_type"] == "machine")]
    if len(state_changes) > 0:
        state_counts = state_changes.groupby(["source", "new_state"]).size().unstack(fill_value=0)
        state_counts.plot(kind="bar", stacked=True, ax=ax, alpha=0.8)
        ax.set_ylabel("State transitions")
        ax.set_title("Machine State Transition Counts")
        ax.tick_params(axis='x', rotation=0)
        ax.legend(fontsize=7, loc="upper right")

    plt.tight_layout()
    output_path = csv_path.replace(".csv", "_analysis.png")
    plt.savefig(output_path, dpi=150)
    print(f"\nPlots saved to: {output_path}")
    plt.close()


def query_influxdb_telegraf(influx_url, influx_token, influx_org, influx_bucket):
    """Query Telegraf-sourced OPC UA data from InfluxDB.

    Returns a dict with data point count, time range, throughput, OEE values,
    per-machine partcounts, and update rate statistics.
    """
    try:
        from influxdb_client import InfluxDBClient
    except ImportError:
        print("ERROR: influxdb-client is required for --influxdb. "
              "Install with: pip install influxdb-client")
        sys.exit(1)

    client = InfluxDBClient(url=influx_url, token=influx_token, org=influx_org)
    query_api = client.query_api()

    result = {}

    # 1. Data point count and time range
    flux = f'''
    from(bucket: "{influx_bucket}")
      |> range(start: 0)
      |> filter(fn: (r) => r._measurement == "opcua")
      |> count()
      |> group()
      |> sum()
    '''
    tables = query_api.query(flux, org=influx_org)
    total_points = 0
    for table in tables:
        for record in table.records:
            total_points += record.get_value()
    result["total_points"] = total_points

    # 2. Time range (first/last SimTime)
    flux_range = f'''
    from(bucket: "{influx_bucket}")
      |> range(start: 0)
      |> filter(fn: (r) => r._measurement == "opcua")
      |> filter(fn: (r) => r._field == "SimTime")
      |> first()
    '''
    tables = query_api.query(flux_range, org=influx_org)
    first_simtime = None
    for table in tables:
        for record in table.records:
            first_simtime = record.get_value()

    flux_range_last = f'''
    from(bucket: "{influx_bucket}")
      |> range(start: 0)
      |> filter(fn: (r) => r._measurement == "opcua")
      |> filter(fn: (r) => r._field == "SimTime")
      |> last()
    '''
    tables = query_api.query(flux_range_last, org=influx_org)
    last_simtime = None
    for table in tables:
        for record in table.records:
            last_simtime = record.get_value()

    result["first_simtime"] = first_simtime
    result["last_simtime"] = last_simtime

    # 3. Final throughput
    flux_throughput = f'''
    from(bucket: "{influx_bucket}")
      |> range(start: 0)
      |> filter(fn: (r) => r._measurement == "opcua")
      |> filter(fn: (r) => r._field == "Throughput")
      |> last()
    '''
    tables = query_api.query(flux_throughput, org=influx_org)
    final_throughput = None
    for table in tables:
        for record in table.records:
            final_throughput = record.get_value()
    result["final_throughput"] = final_throughput

    # 4. Line OEE over time
    flux_oee = f'''
    from(bucket: "{influx_bucket}")
      |> range(start: 0)
      |> filter(fn: (r) => r._measurement == "opcua")
      |> filter(fn: (r) => r._field == "LineOEE")
      |> sort(columns: ["_time"])
    '''
    tables = query_api.query(flux_oee, org=influx_org)
    oee_values = []
    for table in tables:
        for record in table.records:
            oee_values.append({
                "time": record.get_time(),
                "value": record.get_value(),
            })
    result["oee_timeseries"] = oee_values

    # 5. Per-machine partcounts (final values)
    flux_parts = f'''
    from(bucket: "{influx_bucket}")
      |> range(start: 0)
      |> filter(fn: (r) => r._measurement == "opcua")
      |> filter(fn: (r) => r._field == "PartCount")
      |> filter(fn: (r) => r.source_type == "machine")
      |> last()
    '''
    tables = query_api.query(flux_parts, org=influx_org)
    machine_partcounts = {}
    for table in tables:
        for record in table.records:
            source = record.values.get("source", "unknown")
            machine_partcounts[source] = record.get_value()
    result["machine_partcounts"] = machine_partcounts

    # 6. Buffer levels (final)
    flux_buffers = f'''
    from(bucket: "{influx_bucket}")
      |> range(start: 0)
      |> filter(fn: (r) => r._measurement == "opcua")
      |> filter(fn: (r) => r._field == "CurrentLevel")
      |> filter(fn: (r) => r.source_type == "buffer")
      |> last()
    '''
    tables = query_api.query(flux_buffers, org=influx_org)
    buffer_levels = {}
    for table in tables:
        for record in table.records:
            source = record.values.get("source", "unknown")
            buffer_levels[source] = record.get_value()
    result["buffer_levels"] = buffer_levels

    # 7. Update rate (average interval between SimTime updates)
    flux_rate = f'''
    from(bucket: "{influx_bucket}")
      |> range(start: 0)
      |> filter(fn: (r) => r._measurement == "opcua")
      |> filter(fn: (r) => r._field == "SimTime")
      |> sort(columns: ["_time"])
      |> elapsed(unit: 1s)
    '''
    tables = query_api.query(flux_rate, org=influx_org)
    intervals = []
    for table in tables:
        for record in table.records:
            elapsed_val = record.values.get("elapsed", None)
            if elapsed_val is not None and elapsed_val > 0:
                intervals.append(elapsed_val)
    result["update_intervals"] = intervals
    if intervals:
        result["avg_update_rate"] = sum(intervals) / len(intervals)
    else:
        result["avg_update_rate"] = None

    # 8. Data gaps (intervals > 5s)
    gaps = [i for i in intervals if i > 5]
    result["gaps_over_5s"] = len(gaps)

    client.close()
    return result


def compare_csv_telegraf(df, influx_data):
    """Compare CSV historian ground truth against Telegraf/InfluxDB OPC UA data.

    Prints a structured comparison report as section 11 of the analysis.
    Returns (checks_passed, checks_total).
    """
    section("11. CSV vs INFLUXDB (Telegraf OPC UA) COMPARISON")

    checks_passed = 0
    checks_total = 0

    # --- Telegraf data range ---
    print(f"  Telegraf data range:")
    print(f"    Points received:    {influx_data['total_points']:,}")

    first_st = influx_data.get("first_simtime")
    last_st = influx_data.get("last_simtime")
    if first_st is not None and last_st is not None:
        span_hrs = (last_st - first_st) / 3600
        print(f"    Time span:          {first_st} - {last_st} ({span_hrs:.1f} hours)")
    else:
        print(f"    Time span:          N/A")

    avg_rate = influx_data.get("avg_update_rate")
    if avg_rate is not None:
        print(f"    Avg update rate:    {1.0/avg_rate:.2f}/sec (expected: 1.00/sec)")
        checks_total += 1
        if abs(1.0 / avg_rate - 1.0) < 0.05:
            print(f"    PASS: Update rate within 5% of expected")
            checks_passed += 1
        else:
            print(f"    FAIL: Update rate deviates > 5% from expected")
    else:
        print(f"    Avg update rate:    N/A (no interval data)")

    # --- Throughput comparison ---
    print(f"\n  Throughput comparison:")
    prod_summaries = df[df["event_type"] == "PRODUCTION_SUMMARY"]
    csv_final_partcount = None
    if len(prod_summaries) > 0:
        csv_final_partcount = prod_summaries.iloc[-1]["partcount"]
        print(f"    CSV final partcount:      {csv_final_partcount:,}")
    else:
        print(f"    CSV final partcount:      N/A (no PRODUCTION_SUMMARY)")

    telegraf_throughput = influx_data.get("final_throughput")
    if telegraf_throughput is not None:
        print(f"    Telegraf final Throughput: {telegraf_throughput:,}")
    else:
        print(f"    Telegraf final Throughput: N/A")

    checks_total += 1
    if csv_final_partcount is not None and telegraf_throughput is not None:
        if csv_final_partcount == telegraf_throughput:
            print(f"    PASS: Exact match")
            checks_passed += 1
        elif abs(csv_final_partcount - telegraf_throughput) <= 2:
            print(f"    PASS: Within 2 parts (timing mismatch)")
            checks_passed += 1
        else:
            diff = abs(csv_final_partcount - telegraf_throughput)
            print(f"    FAIL: Mismatch of {diff} parts")
    else:
        print(f"    SKIP: Missing data for comparison")

    # --- OEE comparison ---
    print(f"\n  OEE comparison:")
    oee_ts = influx_data.get("oee_timeseries", [])
    checks_total += 1
    if len(oee_ts) > 0 and len(prod_summaries) > 0:
        extras = parse_extra_json(prod_summaries["extra_json"])

        csv_oee_vals = extras.apply(lambda x: x.get("line_oee", None))
        csv_oee_vals = pd.to_numeric(csv_oee_vals, errors="coerce").dropna()

        telegraf_oee_vals = [v["value"] for v in oee_ts if v["value"] is not None]

        if len(csv_oee_vals) > 0 and len(telegraf_oee_vals) > 0:
            csv_mean = csv_oee_vals.mean()
            telegraf_mean = sum(telegraf_oee_vals) / len(telegraf_oee_vals)
            mean_diff = abs(csv_mean - telegraf_mean)
            print(f"    CSV OEE samples:      {len(csv_oee_vals):,} (mean={csv_mean:.4f})")
            print(f"    Telegraf OEE samples:  {len(telegraf_oee_vals):,} (mean={telegraf_mean:.4f})")
            print(f"    Mean absolute diff:    {mean_diff:.4f}")

            if mean_diff < 0.05:
                print(f"    PASS: OEE means within 0.05 tolerance")
                checks_passed += 1
            else:
                print(f"    FAIL: OEE means differ by {mean_diff:.4f}")
        else:
            print(f"    SKIP: Insufficient OEE data for comparison")
    else:
        print(f"    SKIP: No OEE data available (CSV: {len(prod_summaries)}, "
              f"Telegraf: {len(oee_ts)})")

    # --- Per-machine PartCount ---
    print(f"\n  Per-machine PartCount:")
    machine_pcs = influx_data.get("machine_partcounts", {})
    machine_events = df[(df["source_type"] == "machine") & (df["event_type"] == "STATE_CHANGE")]
    csv_machines = sorted(machine_events["source"].unique())

    for i, csv_m in enumerate(csv_machines):
        telegraf_key = f"Machine{i+1}"
        m_events = machine_events[machine_events["source"] == csv_m]
        csv_pc = m_events.iloc[-1]["partcount"] if len(m_events) > 0 else None
        telegraf_pc = machine_pcs.get(telegraf_key)

        checks_total += 1
        csv_str = f"{csv_pc:,}" if csv_pc is not None else "N/A"
        tel_str = f"{telegraf_pc:,}" if telegraf_pc is not None else "N/A"

        if csv_pc is not None and telegraf_pc is not None:
            if abs(csv_pc - telegraf_pc) <= 2:
                print(f"    {telegraf_key}: CSV={csv_str}  Telegraf={tel_str}  PASS")
                checks_passed += 1
            else:
                print(f"    {telegraf_key}: CSV={csv_str}  Telegraf={tel_str}  FAIL")
        else:
            print(f"    {telegraf_key}: CSV={csv_str}  Telegraf={tel_str}  SKIP")

    # --- Buffer levels ---
    print(f"\n  Buffer levels (spot check):")
    buffer_levels = influx_data.get("buffer_levels", {})
    buf_events = df[(df["source_type"] == "buffer") & (df["event_type"] == "STATE_CHANGE")]
    csv_buffers = sorted(buf_events["source"].unique())

    for i, csv_b in enumerate(csv_buffers):
        telegraf_key = f"Buffer{i+1}"
        b_events = buf_events[buf_events["source"] == csv_b]
        csv_level = b_events.iloc[-1]["buffer_level"] if len(b_events) > 0 else None
        telegraf_level = buffer_levels.get(telegraf_key)

        checks_total += 1
        csv_str = str(csv_level) if csv_level is not None else "N/A"
        tel_str = str(telegraf_level) if telegraf_level is not None else "N/A"

        if csv_level is not None and telegraf_level is not None:
            if abs(csv_level - telegraf_level) <= 1:
                print(f"    {telegraf_key} final: CSV={csv_str}  Telegraf={tel_str}  PASS")
                checks_passed += 1
            else:
                print(f"    {telegraf_key} final: CSV={csv_str}  Telegraf={tel_str}  FAIL")
        else:
            print(f"    {telegraf_key} final: CSV={csv_str}  Telegraf={tel_str}  SKIP")

    # --- Data gaps ---
    print(f"\n  Data gaps (Telegraf):")
    gaps = influx_data.get("gaps_over_5s", 0)
    checks_total += 1
    print(f"    Gaps > 5s: {gaps}")
    if gaps == 0:
        print(f"    PASS: No significant gaps")
        checks_passed += 1
    elif gaps <= 3:
        print(f"    WARN: {gaps} minor gaps detected")
        checks_passed += 1  # Still pass for minor gaps
    else:
        print(f"    FAIL: {gaps} significant gaps detected")

    # --- Verdict ---
    print(f"\n  Pipeline verdict: ", end="")
    if checks_passed == checks_total:
        print(f"ALL CHECKS PASSED ({checks_passed}/{checks_total})")
    else:
        print(f"SOME CHECKS FAILED ({checks_passed}/{checks_total})")

    return checks_passed, checks_total


def main():
    parser = argparse.ArgumentParser(description="Analyze historian CSV files")
    parser.add_argument("path", help="CSV file path or directory (auto-picks latest)")
    parser.add_argument("--plot", action="store_true", help="Generate matplotlib plots")
    parser.add_argument("--influxdb", action="store_true",
                        help="Enable InfluxDB comparison (Telegraf-sourced data)")
    parser.add_argument("--influxdb-url", default=None,
                        help="InfluxDB URL (default: env INFLUXDB_URL or http://localhost:8086)")
    parser.add_argument("--influxdb-token", default=None,
                        help="InfluxDB token (default: env INFLUXDB_TOKEN)")
    parser.add_argument("--influxdb-org", default=None,
                        help="InfluxDB org (default: env INFLUXDB_ORG or 'simantha')")
    parser.add_argument("--influxdb-bucket", default=None,
                        help="InfluxDB bucket (default: env INFLUXDB_BUCKET or 'manufacturing')")
    args = parser.parse_args()

    # Resolve path
    if os.path.isdir(args.path):
        csv_path = find_latest_csv(args.path)
        print(f"Auto-selected latest file: {csv_path}")
    else:
        csv_path = args.path

    if not os.path.exists(csv_path):
        print(f"File not found: {csv_path}")
        sys.exit(1)

    # Load and analyze
    print(f"Loading {csv_path}...")
    df = load_csv(csv_path)
    prod_summaries = analyze(df, csv_path)

    if args.plot:
        plot_analysis(df, prod_summaries, csv_path)

    # InfluxDB comparison (Telegraf OPC UA pipeline validation)
    if args.influxdb:
        influx_url = (args.influxdb_url
                      or os.environ.get("INFLUXDB_URL", "http://localhost:8086"))
        influx_token = (args.influxdb_token
                        or os.environ.get("INFLUXDB_TOKEN"))
        influx_org = (args.influxdb_org
                      or os.environ.get("INFLUXDB_ORG", "simantha"))
        influx_bucket = (args.influxdb_bucket
                         or os.environ.get("INFLUXDB_BUCKET", "manufacturing"))

        if not influx_token:
            print("\nERROR: --influxdb-token or INFLUXDB_TOKEN env var is required")
            sys.exit(1)

        print(f"\nQuerying InfluxDB at {influx_url} ...")
        influx_data = query_influxdb_telegraf(influx_url, influx_token, influx_org, influx_bucket)
        compare_csv_telegraf(df, influx_data)


if __name__ == "__main__":
    main()
